arch = computer;

libpath = sprintf("extern/lib/%s/clapack", arch);
signatures = [ ...
    '["dgetrf_","i33p3p3",{"3":{"type":"fadr","out":1},"5":{"type":"fai","out":1},"6":{"out":1}}]' ...
    ;'["dgetri_","i3p3pp33",{"2":{"type":"fadr","out":1},"4":{"type":"fai"},"5":{"type":"fadr","out":1},"7":{"out":1}}]' ...
    %;"zgetrf_;i33p3p3" ...
    %;"zgetri_;i3p3pp33" ...
    ];
loadlibrary(libpath, signatures, 'CLAPACK');



